# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200401_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hakkam', models.IntegerField(default=5)),
                ('current_bid', models.IntegerField(default=150)),
                ('winning_bid', models.IntegerField(default=None, null=True)),
                ('partner1', models.IntegerField(default=None, null=True)),
                ('partner2', models.IntegerField(default=None, null=True)),
                ('partner1card', models.IntegerField(default=None, null=True)),
                ('partner2card', models.IntegerField(default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('points', models.IntegerField(default=None, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='chat.Game')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HandEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_played', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chat.Hand')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['handle']},
        ),
        migrations.AddField(
            model_name='handentry',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='hand_winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='bid_winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='chat.Room'),
        ),
        migrations.AddField(
            model_name='bid',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='chat.Game'),
        ),
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Player'),
        ),
    ]
