# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200403_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='cards_played',
            field=models.TextField(default='[]'),
        ),
    ]
