# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_hand_cards_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='first_suit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
