# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_hand_first_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='partner1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='partner2',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='cards_played',
        ),
        migrations.AddField(
            model_name='game',
            name='cards',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='partnerplayer1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_partner1', to='chat.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='partnerplayer2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_partner2', to='chat.Player'),
        ),
    ]
