# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-04 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200404_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='partnerplayer1',
            new_name='partner1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='partnerplayer2',
            new_name='partner2',
        ),
    ]
